#
# Spring Petclinic, Docker Compose configuration file
#
# Required variables: none
# Optional variables: none
#
# Usage:
#  docker-compose -f local.yml up [ -d ]
#

version: '2'

services:
    petclinicserver:
        image: ${dockerRepository}/petclinic-api-server:${project.version}
        ports:
            - "8080"
